### ISSUE TITLE
make those functions marked with TODO work with change in focus from shortest distance to maxGH/Euclidean distance

### ISSUE THREAD

**Issue by bdolor** [bdolor/groups-hybrid#2]
functions marked with TODO need to be refactored:

https://github.com/bdolor/groups-hybrid/blob/master/src/main/java/GroupsHybrid/AntColony/Structure/AntColonyArray.java#L60

https://github.com/bdolor/groups-hybrid/blob/master/src/main/java/GroupsHybrid/AntColony/Structure/AntColonyArray.java#L80

https://github.com/bdolor/groups-hybrid/blob/master/src/main/java/GroupsHybrid/AntColony/Structure/AntColonyArray.java#L106

https://github.com/bdolor/groups-hybrid/blob/master/src/main/java/GroupsHybrid/AntColony/Structure/AntColonyArray.java#L140

https://github.com/bdolor/groups-hybrid/blob/master/src/main/java/GroupsHybrid/AntColony/Structure/AntColonyArray.java#L177

**Comment by bdolor** [comment]
@Matt-KA - can you take a look at these? I've changed the variable `distances` to mean Euclidean distances and modified the `bestTrail` to mean the one with the maxGH. Changing those two things will now affect how `updateTrials` `updatePheremones`, etc will play out.

**Comment by Matt-KA** [comment]
Hey Brad yes I'll have a look.

Did you write all of this yourself or do bits and pieces come from other
sources?  I'd love to get inside your head a little and how you go about
building this.

On Fri, Nov 27, 2015 at 7:00 PM, Brad notifications@github.com wrote:

> @Matt-KA https://github.com/Matt-KA - can you take a look at these?
> I've changed the variable distances to mean Euclidean distances and
> modified the bestTrail to mean the one with the maxGH. Changing those two
> things will now affect how updateTrials updatePheremones, etc will play
> out.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdolor/groups-hybrid/issues/2#issuecomment-160228035.

## 

Rise above principle and do what's right.  -  Joseph Heller

**Comment by bdolor** [comment]
Hey Matt, this code has been refactored from https://github.com/gappc/aco 
All appropriate attributions have yet to be added, so please feel free to do so. 

I'm thinking that we modify the ACO algorithm to deal with the specific objective that we discussed via email. Once that's done, we will have a working GA that solves the problem and a working ACO that solves the problem. Hybridization should be relatively straight forward after that.

**Comment by Matt-KA** [comment]
Ok sounds like a plan.

On Fri, Nov 27, 2015 at 7:25 PM, Brad notifications@github.com wrote:

> Hey Matt, this code has been refactored from https://github.com/gappc/aco
> All appropriate attributions have yet to be added, so please feel free to
> do so.
> 
> I'm thinking that we modify the ACO algorithm to deal with the specific
> objective that we discussed via email. Once that's done, we will have a
> working GA that solves the problem and a working ACO that solves the
> problem. Hybridization should be relatively straight forward after that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdolor/groups-hybrid/issues/2#issuecomment-160229228.

## 

Rise above principle and do what's right.  -  Joseph Heller

**Comment by Matt-KA** [comment]
Hi Brad,

```
  I'm having a problem with some of the jars required to build the
```

project.  Is there a repo somewhere where there's a folder with these
libraries?

-Matt
[image: Inline image 1]

On Fri, Nov 27, 2015 at 7:28 PM, Matthew Arsenault <
matt.k.arsenault@gmail.com> wrote:

> Ok sounds like a plan.
> 
> On Fri, Nov 27, 2015 at 7:25 PM, Brad notifications@github.com wrote:
> 
> > Hey Matt, this code has been refactored from https://github.com/gappc/aco
> > All appropriate attributions have yet to be added, so please feel free to
> > do so.
> > 
> > I'm thinking that we modify the ACO algorithm to deal with the specific
> > objective that we discussed via email. Once that's done, we will have a
> > working GA that solves the problem and a working ACO that solves the
> > problem. Hybridization should be relatively straight forward after that.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/bdolor/groups-hybrid/issues/2#issuecomment-160229228
> > .
> 
> ## 
> 
> Rise above principle and do what's right.  -  Joseph Heller

## 

Rise above principle and do what's right.  -  Joseph Heller

**Comment by bdolor** [comment]
resolved via https://github.com/bdolor/groups-hybrid/commit/267a3dd3a22df76af2debe3b17b778459685d45a

**Comment by Matt-KA** [comment]
thanks!

On Fri, Nov 27, 2015 at 10:47 PM, Brad notifications@github.com wrote:

> resolved via 267a3dd
> https://github.com/bdolor/groups-hybrid/commit/267a3dd3a22df76af2debe3b17b778459685d45a
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdolor/groups-hybrid/issues/2#issuecomment-160244309.

## 

Rise above principle and do what's right.  -  Joseph Heller

**Comment by bdolor** [comment]
Any progress with this, or can I dive in knowing that I'm not stepping on anything you've done?

**Comment by Matt-KA** [comment]
Not a lot just yet unfortunately.

On Sun, Nov 29, 2015 at 7:24 PM, Brad notifications@github.com wrote:

> Any progress with this, or can I dive in knowing that I'm not stepping on
> anything you've done?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bdolor/groups-hybrid/issues/2#issuecomment-160486520.

## 

Rise above principle and do what's right.  -  Joseph Heller

**Comment by bdolor** [comment]
closing via https://github.com/bdolor/groups-hybrid/commit/797e5fda6a54f2dc0138672dfc2b4681af5f25c0
